FROM minio/minio:latest

LABEL maintainer="MinIO Inc <dev@min.io>"

COPY minio /usr/bin/

EXPOSE 9000

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

HEALTHCHECK --interval=1m CMD healthcheck

CMD ["minio"]
