// Code generated by "stringer -type=storageMetric -trimprefix=storageMetric xl-storage-disk-id-check.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[storageMetricIsOnline-1]
	_ = x[storageMetricHealing-2]
	_ = x[storageMetricGetDiskID-3]
	_ = x[storageMetricDiskInfo-4]
	_ = x[storageMetricMakeVolBulk-5]
	_ = x[storageMetricMakeVol-6]
	_ = x[storageMetricListVols-7]
	_ = x[storageMetricStatVol-8]
	_ = x[storageMetricDeleteVol-9]
	_ = x[storageMetricWalkVersions-10]
	_ = x[storageMetricWalkDir-11]
	_ = x[storageMetricListDir-12]
	_ = x[storageMetricReadFile-13]
	_ = x[storageMetricAppendFile-14]
	_ = x[storageMetricCreateFile-15]
	_ = x[storageMetricReadFileStream-16]
	_ = x[storageMetricRenameFile-17]
	_ = x[storageMetricRenameData-18]
	_ = x[storageMetricCheckParts-19]
	_ = x[storageMetricCheckFile-20]
	_ = x[storageMetricDelete-21]
	_ = x[storageMetricDeleteVersions-22]
	_ = x[storageMetricVerifyFile-23]
	_ = x[storageMetricWriteAll-24]
	_ = x[storageMetricDeleteVersion-25]
	_ = x[storageMetricWriteMetadata-26]
	_ = x[storageMetricReadVersion-27]
	_ = x[storageMetricReadAll-28]
	_ = x[metricLast-29]
}

const _storageMetric_name = "IsOnlineHealingGetDiskIDDiskInfoMakeVolBulkMakeVolListVolsStatVolDeleteVolWalkVersionsWalkDirListDirReadFileAppendFileCreateFileReadFileStreamRenameFileRenameDataCheckPartsCheckFileDeleteDeleteVersionsVerifyFileWriteAllDeleteVersionWriteMetadataReadVersionReadAllmetricLast"

var _storageMetric_index = [...]uint16{0, 8, 15, 24, 32, 43, 50, 58, 65, 74, 86, 93, 100, 108, 118, 128, 142, 152, 162, 172, 181, 187, 201, 211, 219, 232, 245, 256, 263, 273}

func (i storageMetric) String() string {
	i -= 1
	if i >= storageMetric(len(_storageMetric_index)-1) {
		return "storageMetric(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _storageMetric_name[_storageMetric_index[i]:_storageMetric_index[i+1]]
}
